language: clojure
lein: lein2
script: lein midje
jdk:
- openjdk7
branches:
  except:
  - gh-pages
env:
  global:
  - GH_REF: github.com/avishai-ish-shalom/riemann-elasticsearch-plugin.git
  - secure: AhfSZxIl5L9m/ALPkJZSJTJrcj5P7zLULLybtVBNuVGKtYlKnqxDazh2sk/0Lra6aeMOfWUmkmZfF5c5QFtBuQhDXc2/RMSCmgZOTdzF7j8t6n2ftQ8qg1yzJBjOXX53AhUmMqJEWf2HB5+UNJBBDGH60QlTrdDNJcBceSqfXpc=

after_script: |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    lein doc
    git fetch origin gh-pages 
    git checkout -b gh-pages origin/gh-pages
    cp -a doc/* ./
    git add -u
    git config user.name "Travis Builder"
    git config user.email "builder@travis.com"
    if git diff-index HEAD; then
      git commit -m "Automatic doc build #{TRAVIS_BUILD_NUMBER}"
      git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages
    fi
  fi
